name: Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: [main]

permissions: read-all

jobs:
  call-scorecard:
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    uses: ulises2k/security-workflows/.github/workflows/scorecard-reusable.yml@main
